tasks:
  - init: pip install -r requirements.txt
  - command: python serve_static.py
  - command: python proxy_server.py

ports:
  - port: 8000
    onOpen: open-preview
  - port: 8888
    onOpen: ignore
